# Generated by Django 4.2.5 on 2023-09-22 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
        migrations.AlterField(
            model_name='server',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
