# Generated by Django 4.2.5 on 2023-09-22 05:03

from django.db import migrations, models
import server.models.category


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_alter_category_options_category_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.category.category_icon_path),
        ),
    ]
