# Generated by Django 4.2.5 on 2023-09-22 05:51

from django.db import migrations, models
import server.models.server


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server.server_banner_path),
        ),
        migrations.AddField(
            model_name='server',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=server.models.server.server_icon_path),
        ),
    ]
